GigHub/Controllers/Api/GigsController.cs
using GigHub.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Http;

namespace GigHub.Controllers.Api
{
    [Authorize]
    public class GigsController : ApiController
    {
        ApplicationDbContext _context;

        public GigsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        [HttpDelete]
        public IHttpActionResult Cancel(int id)
        {
            var userId = User.Identity.GetUserId();
            var gig = (from g in _context.Gigs
                       where !g.IsCancelled
                       && g.Id == id
                       && g.ArtistId == userId
                       select g).SingleOrDefault();

            if (gig == null)
                return NotFound();

            gig.IsCancelled = true;
            _context.SaveChanges();
            return Ok("Cancelled the Gig Successfuly");
        }
    }
}

GigHub/Views/Shared/_GigListPartial.cshtml
@model GigHub.ViewModels.GigsViewModel
<h3>@Model.Heading</h3>
<hr />

@if (Model.Gigs.Any())
{
    <ul class="gigs">
        @foreach (var gig in Model.Gigs)
        {
            @*<li>@item.DateTime - @item.Artist.Name</li>*@
            <li>
                <div class="date">
                    <div class="month">
                        @string.Format("{0:MMM}", gig.DateTime)
                    </div>
                    <div class="day">
                        @string.Format("{0:dd}", gig.DateTime)
                    </div>
                </div>
                <div class="details">
                    <span class="artist">
                        @gig.Artist.Name
                        @if (gig.IsCancelled)
                        {
                            <span class="label label-warning">Canceled</span>
                        }
                        @if (Model.ShowActions)
                        {
                            <button class="btn btn-link btn-sm js-toggle-following"
                                    data-artist-id="@gig.ArtistId">
                                Following?
                            </button>
                        }
                    </span>

                    <span class="genre">
                        @gig.Genre.Name
                    </span>
                    @if (Model.ShowActions && !gig.IsCancelled)
                    {
                        <button class="btn btn-default btn-sm pull-right js-toggle-attendance"
                                data-gig-id="@gig.Id">
                            Going?
                        </button>
                    }
                </div>
                <div>
                    <div class="day"></div>
                </div>
                <div class="details">
                    <span class="artist"></span>
                    <span class="genre"></span>
                </div>

            </li>
        }
    </ul>
}
else
{
    <p>No upcoming gigs to display</p>
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            $('.js-toggle-attendance').click(function (e) {
                var btn = $(e.target);
                $.post("/api/Attendances", { gigId: btn.attr("data-gig-id") })
                .done(function () {
                    btn
                        .removeClass("btn-default")
                        .addClass("btn-info")
                        .text("Going");
                })
                .fail(function (xhr, status, error) {
                    debugger
                    var err = eval("(" + xhr.responseText + ")");
                    alert("Something failed - " + err.Message);
                })
            });

            $('.js-toggle-following').click(function (e) {
                var btn = $(e.target);
                debugger;
                $.post("/api/FollowingArtist", { artistId: btn.attr("data-artist-id") })
                .done(function () {
                    btn
                        .removeClass("btn-default")
                        .addClass("btn-info")
                        .text("Following");
                })
                .fail(function (xhr, status, error) {
                    debugger
                    var err = eval("(" + xhr.responseText + ")");
                    alert("Something failed - " + err.Message);
                })
            });
        });
    </script>
}

GigHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -GigHub</title>

    @*Adding google fonts downloads link*@
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Montserrat|Open+Sans:400,700" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("topNavPartial")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GigHub</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GigHub/Views/Shared/topNavPartial.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("GigHub", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">               
                <li>@Html.ActionLink("Add a Gig", "Create", "Gigs")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>